import { CssProperty, Property, Style, View } from '@nativescript/core';
export declare const checkedProperty: any;
export declare const textProperty: Property<CheckBox, string>;
export declare const fillColorProperty: CssProperty<Style, string>;
export declare const tintColorProperty: CssProperty<Style, string>;
export declare const fontSizeProperty: CssProperty<Style, number>;
export declare class CheckBox extends View {
    checked: boolean;
    nativeView: androidx.appcompat.widget.AppCompatCheckBox;
    private _android;
    private _boxType;
    private _checkStyle;
    private _checkPadding;
    private _checkPaddingLeft;
    private _checkPaddingTop;
    private _checkPaddingRight;
    private _checkPaddingBottom;
    constructor();
    get android(): androidx.appcompat.widget.AppCompatCheckBox;
    set boxType(value: string);
    get boxType(): string;
    get checkStyle(): string;
    set checkStyle(style: string);
    set checkPadding(padding: string);
    get checkPadding(): string;
    set checkPaddingLeft(padding: string);
    get checkPaddingLeft(): string;
    set checkPaddingTop(padding: string);
    get checkPaddingTop(): string;
    set checkPaddingRight(padding: string);
    get checkPaddingRight(): string;
    set checkPaddingBottom(padding: string);
    get checkPaddingBottom(): string;
    get fillColor(): string;
    set fillColor(color: string);
    get tintColor(): string;
    set tintColor(color: string);
    createNativeView(): androidx.appcompat.widget.AppCompatCheckBox;
    initNativeView(): void;
    disposeNativeView(): void;
    toggle(): void;
    _onCheckedPropertyChanged(checkbox: CheckBox, oldValue: any, newValue: any): void;
    _onTextPropertyChanged(checkbox: CheckBox, oldValue: any, newValue: any): void;
}
